export const typingTestTexts = [
    `El rápido zorro marrón salta sobre el perro perezoso. Este es un ejercicio clásico de mecanografía para practicar todas las letras del alfabeto en una sola oración. Al repetir esta frase, se mejora la velocidad y la precisión de la escritura. Además, ayuda a familiarizarse con la disposición del teclado y a desarrollar la memoria muscular necesaria para escribir sin mirar las teclas. Con el tiempo, los mecanógrafos pueden notar una mejora significativa en su capacidad para escribir rápidamente y sin errores.`,
    `En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lentejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda. El resto della concluían sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mismo, y los días de entresemana se honraba con su vellori de lo más fino.`,
    `Ayer, todos mis problemas parecían tan lejanos. Ahora parece que están aquí para quedarse. Oh, creo en el ayer. De repente, no soy la mitad del hombre que solía ser. Hay una sombra que se cierne sobre mí. Oh, el ayer vino de repente. ¿Por qué ella tuvo que irse? No lo sé, no lo diría. Dije algo mal, ahora anhelo el ayer. Ayer, el amor era un juego tan fácil de jugar. Ahora necesito un lugar para esconderme. Oh, creo en el ayer.`,
    `Ser o no ser, esa es la cuestión. Si es más noble en la mente sufrir los tiros y flechas de la fortuna atroz, o tomar las armas contra un mar de problemas y, haciéndoles frente, acabar con ellos. Morir, dormir, no más. Y con un sueño decir que terminamos con el pesar del corazón y los mil conflictos naturales que constituyen la herencia de la carne. Es una consumación devotamente deseada. Morir, dormir, dormir, tal vez soñar. Sí, ahí está el obstáculo. Porque en ese sueño de la muerte, los sueños pueden venir, cuando hemos despojado esta mortal envoltura, deben hacernos detenernos.`,
    `La educación es el arma más poderosa que puedes usar para cambiar el mundo. Nelson Mandela comprendía profundamente la importancia de la educación en la transformación de las sociedades. A través del conocimiento y el aprendizaje, las personas pueden empoderarse para alcanzar sus sueños y contribuir positivamente a sus comunidades. La educación no solo abre puertas a oportunidades laborales, sino que también fomenta la comprensión, la tolerancia y la paz. En un mundo en constante cambio, la educación sigue siendo un pilar fundamental para el desarrollo sostenible y el progreso global.`,
    `La vida es lo que pasa mientras estás ocupado haciendo otros planes. Esta famosa cita de John Lennon destaca la importancia de vivir el momento y apreciar lo que tenemos en el presente. A menudo, nos encontramos atrapados en la rutina diaria, preocupándonos por el futuro o lamentando el pasado. Sin embargo, la verdadera felicidad y realización se encuentran en aprender a disfrutar el aquí y el ahora. Al enfocarnos en el presente, podemos encontrar la belleza en las pequeñas cosas y construir recuerdos valiosos que durarán toda la vida. La vida es corta y frágil, y es crucial hacer cada día significativo.`,
    `La imaginación es más importante que el conocimiento. Albert Einstein valoraba la imaginación por encima del conocimiento porque creía que la capacidad de imaginar es lo que impulsa la innovación y el progreso. Mientras que el conocimiento es limitado a lo que sabemos y entendemos actualmente, la imaginación no tiene fronteras. Nos permite explorar nuevas ideas, conceptos y mundos, abriendo puertas a posibilidades infinitas. Fomenta la creatividad y nos inspira a buscar soluciones innovadoras a los problemas. En un mundo en constante evolución, la imaginación sigue siendo un motor vital para el desarrollo humano y científico.`,
    `El éxito es ir de fracaso en fracaso sin perder el entusiasmo. Esta cita de Winston Churchill subraya la importancia de la perseverancia y la actitud positiva ante los desafíos. El camino al éxito está lleno de obstáculos y reveses, pero aquellos que mantienen su determinación y entusiasmo a pesar de las dificultades son los que finalmente alcanzan sus metas. Aprender de los fracasos y seguir adelante con una mentalidad optimista es clave para superar las adversidades y triunfar en cualquier ámbito de la vida. El éxito no se mide solo por los logros, sino también por la resistencia y el espíritu con que enfrentamos las pruebas.`,
    `La vida es como andar en bicicleta. Para mantener el equilibrio, debes seguir adelante. Albert Einstein utilizó esta metáfora para explicar la importancia de la perseverancia y el movimiento continuo. En la vida, enfrentamos muchos desafíos y obstáculos, pero debemos seguir avanzando para mantenernos en equilibrio. Detenernos o rendirnos solo nos llevará a perder el equilibrio y caer. La clave es mantenernos en movimiento, aprender de nuestros errores y adaptarnos a las circunstancias cambiantes. Con cada pedalada, ganamos fuerza, experiencia y confianza para enfrentar el siguiente tramo del viaje.`,
    `El futuro pertenece a aquellos que creen en la belleza de sus sueños. Eleanor Roosevelt entendía que los sueños y las aspiraciones son el motor que impulsa a las personas a alcanzar grandes logros. Creer en nuestros sueños nos da la motivación y la fuerza para superar los obstáculos y trabajar hacia nuestras metas. La visión de un futuro mejor nos inspira a tomar acción y a hacer realidad nuestras esperanzas y deseos. Aquellos que se atreven a soñar y a perseguir sus sueños con pasión y determinación son los que moldean el futuro y dejan un legado duradero.`
];
  